kind: Namespace
apiVersion: v1
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${AZURE_COSMOS_CLIENTID}
  name: ${NAMESPACE}-sa
  namespace: ${NAMESPACE}
