apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-base-config
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: contoso-air-base
    kubernetes.azure.com/generator: devhub
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
