apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${AZURE_COSMOS_CLIENTID}
  labels:
    azure.workload.identity/use: "true"
  name: ${NAMESPACE}-sa
  namespace: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-air-base
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: contoso-air-base
    kubernetes.azure.com/generator: devhub
    azure.workload.identity/use: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: contoso-air-base
  template:
    metadata:
      labels:
        app.kubernetes.io/name: contoso-air-base
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${NAMESPACE}-sa
      containers:
        - name: contoso-air-base
          image: 
            gmay25clu2registry.azurecr.io/image-workflow-1745776707818:892f050fd396da0f7ea56dd899788f7d1b177833
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: contoso-air-base-config
            - secretRef:
                name: secret-ref
                optional: true
            - secretRef:
                name: app-secrets
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
          startupProbe:
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
                - SYS_PTRACE
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: acr-repo-sec01
        - namespace: default
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: contoso-air-base
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: contoso-air-base
      
