apiVersion: v1
kind: Namespace
metadata:
  name: contosoair01
  labels:
    app.kubernetes.io/name: contoso-air-base
    kubernetes.azure.com/generator: devhub
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/use: "true"
    kubernetes.azure.com/generator: devhub