apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  AZURE_COSMOS_CLIENTID: ${AZURE_COSMOS_CLIENTID}
  AZURE_COSMOS_LISTCONNECTIONSTRINGURL: https://management.azure.com${AZURE_COSMOS_LISTCONNECTIONSTRINGURL}/listConnectionStrings?api-version=2024-11-15
  AZURE_COSMOS_RESOURCEENDPOINT: ${AZURE_COSMOS_RESOURCEENDPOINT}
  AZURE_COSMOS_SCOPE: ${AZURE_COSMOS_SCOPE}
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-repo-sec01
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  docker-server: ${DOCKER-SERVER}
  docker-username: ${DOCKER-USERNAME}
  docker-password: ${DOCKER-PASSWORD}