apiVersion: v1
kind: Service
metadata:
  name: contoso-air-base
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: contoso-air-base
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: contoso-air-base
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000