kind: Namespace
apiVersion: v1
metadata:
  name: app-name
  labels:
    team: teamname
    az-rgroup: resource-group
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: kubernetes.azure.com/fips_enabled=true

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: small-quota
  namespace: app-name
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-default-small
  namespace: app-name
spec:
  minAvailable: 30%
  selector: {} #branch test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-name
  namespace: argocd
spec:
  project: default
  source:    
    repoURL: repourl
    targetRevision: branch
    path: repopath
    helm:
      valuesObject:
        namespace:
          name: app-name
        serviceaccount:
          clientId: myclientid
        scrprovclass:
          keyVaultname: mykeyvaultname
          tenantId: mytenantid
  syncPolicy:
      automated: {}
  destination:
      namespace: app-name
      server: https://kubernetes.default.svc
