kind: Namespace
apiVersion: v1
metadata:
  name: $appname
  labels:
    name: $teamname
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $appname
  namespace: argocd
spec:
  project: default
  source:
    repoURL: $repourl
    targetRevision: HEAD
    path: $repopath
  destination:
    server: https://kubernetes.default.svc
    namespace: $appname
