apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: pc-test-clu1
spec:
  credentials:
    source: Secret
    secretRef:
      name: test-clu1-cred
      namespace: upbound-system
      key: kubeconfig
